POST http://localhost:8080/consultants
Content-Type: application/json

{
  "email" : "consultant@service.com",
  "nickName" : "consultant",
  "name" : "상담사",
  "password" : "password",
  "confirmPassword": "password",
  "gender" : "MALE",
  "phoneNumber" : "821012345678",
  "birthday": "2000-01-01",
  "role" : "ROLE_CONSULTANT"
}